### PR TITLE
Add documentation of Annotations Restored format

### PR DESCRIPTION
**Pull request by tech234a**
I hope this is right, as I was basing this on what I saw in the code. Addresses #3.

### CODE REVIEW

**Comment by afrmtbl** [comment]
The `x`, `y`, `w`, and `h` properties are in percent (of the video width and height) instead of pixels. Also, `as` is the time (in seconds) the annotation will seek to when clicked on. As far as I know, an annotation will either have no action, or a url. A url that just links back to the same video with a timestamp is converted into `as=TIME`.  Other than that it looks good! Sorry, I know the names are a pretty hard to decipher but I was just trying to get them as short as possible because of the description length limitation.

Kind of unrelated for this issue but, while I was trying to find out what a "pause" annotation is, I found a decent amount of complaints saying that they were annoying, so I left them out for now. Perhaps they shouldn't be supported?

**Comment by afrmtbl** [comment]
Also kind of unrelated but I also updated the converter so it keeps a list of unique properties that it encounters while parsing (you can also upload multiple files at once for gathering data, the lists are additive). This is what I was able to get after loading all my annotation data (xml + json dumps from omarroth):
image

Let me know if you can get anything I don't have with your data.

**Comment by tech234a** [comment]
@afrmtbl I revised the pull request. As for pause annotations, they have already been gone for several years (here is a video discussing their removal in 2013 - https://www.youtube.com/watch?v=N3ZekDlz4o0). I think that they should be available as an option for Annotations Restored, but maybe not enabled by default because they have been disabled for so long.

**Comment by tech234a** [comment]
Also, nice work on the converter! I have been using a very small set of data, so you have more properties than I did.

**Pull request merged**
